// <auto-generated />
using System;
using HotelBooking.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooking.Infrastructure.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20250819184001_alter_sp_SearchHotelRoomAmenities")]
    partial class alter_sp_SearchHotelRoomAmenities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Core.DTO.HotelDto.RoomSearchDto", b =>
                {
                    b.Property<string>("AccessibilityFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<string>("HotelLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("RoomSearchDtos");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("AmenityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AmenityID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityID = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Free high-speed internet",
                            IsActive = true,
                            Name = "WiFi"
                        },
                        new
                        {
                            AmenityID = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Air-conditioned rooms",
                            IsActive = true,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            AmenityID = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complimentary breakfast",
                            IsActive = true,
                            Name = "Breakfast"
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Cancellation", b =>
                {
                    b.Property<int>("CancellationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CancellationID"));

                    b.Property<DateTime>("CancellationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CancellationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancellationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("CancellationID");

                    b.HasIndex("ReservationID");

                    b.ToTable("Cancellations");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = 1,
                            CountryCode = "NP",
                            CountryName = "Nepal",
                            IsActive = true
                        },
                        new
                        {
                            CountryID = 2,
                            CountryCode = "IN",
                            CountryName = "India",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FeedbackDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.HasIndex("GuestID");

                    b.HasIndex("ReservationID");

                    b.ToTable("Feedbacks", t =>
                        {
                            t.HasCheckConstraint("CHK_Rating", "Rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Guest", b =>
                {
                    b.Property<int>("GuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("GuestID");

                    b.HasIndex("CountryID");

                    b.HasIndex("StateID");

                    b.HasIndex("UserID");

                    b.ToTable("Guests", t =>
                        {
                            t.HasCheckConstraint("CHK_AgeGroup", "AgeGroup IN ('Adult', 'Child', 'Infant')");
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            Address = "",
                            City = "Kathmandu",
                            Country = "Nepal",
                            Description = "",
                            Email = "info@sunrise.com",
                            Name = "Sunrise Hotel",
                            PhoneNumber = "",
                            StarRating = 4
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.HotelImage", b =>
                {
                    b.Property<int>("HotelImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelImageId"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelImageId");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelImages");

                    b.HasData(
                        new
                        {
                            HotelImageId = 1,
                            Caption = "Front View",
                            HotelId = 1,
                            ImageUrl = "/images/hotels/sunrise1.jpg"
                        },
                        new
                        {
                            HotelImageId = 2,
                            Caption = "Lobby",
                            HotelId = 1,
                            ImageUrl = "/images/hotels/sunrise2.jpg"
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaymentBatchID")
                        .HasColumnType("int");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("PaymentBatchID");

                    b.HasIndex("ReservationID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.PaymentBatch", b =>
                {
                    b.Property<int>("PaymentBatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentBatchID"));

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PaymentBatchID");

                    b.HasIndex("UserID");

                    b.ToTable("PaymentBatches");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Refund", b =>
                {
                    b.Property<int>("RefundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundID"));

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RefundDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RefundMethodID")
                        .HasColumnType("int");

                    b.Property<string>("RefundReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefundStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefundID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("ProcessedByUserID");

                    b.HasIndex("RefundMethodID");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.RefundMethod", b =>
                {
                    b.Property<int>("MethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MethodID");

                    b.ToTable("RefundMethods");

                    b.HasData(
                        new
                        {
                            MethodID = 1,
                            IsActive = true,
                            MethodName = "Cash"
                        },
                        new
                        {
                            MethodID = 2,
                            IsActive = true,
                            MethodName = "Credit Card"
                        },
                        new
                        {
                            MethodID = 3,
                            IsActive = true,
                            MethodName = "Bank Transfer"
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("RoomID");

                    b.HasIndex("UserID");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasCheckConstraint("CHK_CheckOutDate", "CheckOutDate > CheckInDate");
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.ReservationGuest", b =>
                {
                    b.Property<int>("ReservationGuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationGuestID"));

                    b.Property<int>("GuestID")
                        .HasColumnType("int");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("ReservationGuestID");

                    b.HasIndex("GuestID");

                    b.HasIndex("ReservationID");

                    b.ToTable("ReservationGuests");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.HasIndex("RoomTypeID");

                    b.ToTable("Rooms", t =>
                        {
                            t.HasCheckConstraint("CHK_Status", "Status IN ('Available', 'Under Maintenance', 'Occupied')");
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.RoomAmenity", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.Property<int>("AmenityID")
                        .HasColumnType("int");

                    b.Property<int>("RoomAmenityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomAmenityID"));

                    b.HasKey("RoomTypeID", "AmenityID");

                    b.HasIndex("AmenityID");

                    b.ToTable("RoomAmenities");

                    b.HasData(
                        new
                        {
                            RoomTypeID = 1,
                            AmenityID = 1,
                            RoomAmenityID = 1
                        },
                        new
                        {
                            RoomTypeID = 1,
                            AmenityID = 2,
                            RoomAmenityID = 2
                        },
                        new
                        {
                            RoomTypeID = 2,
                            AmenityID = 1,
                            RoomAmenityID = 3
                        },
                        new
                        {
                            RoomTypeID = 2,
                            AmenityID = 2,
                            RoomAmenityID = 4
                        },
                        new
                        {
                            RoomTypeID = 2,
                            AmenityID = 3,
                            RoomAmenityID = 5
                        },
                        new
                        {
                            RoomTypeID = 3,
                            AmenityID = 1,
                            RoomAmenityID = 6
                        },
                        new
                        {
                            RoomTypeID = 3,
                            AmenityID = 2,
                            RoomAmenityID = 7
                        },
                        new
                        {
                            RoomTypeID = 3,
                            AmenityID = 3,
                            RoomAmenityID = 8
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.RoomType", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeID"));

                    b.Property<string>("AccessibilityFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeID");

                    b.HasIndex("HotelId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeID = 1,
                            AccessibilityFeatures = "Wheelchair Accessible",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Single bed room",
                            HotelId = 1,
                            IsActive = true,
                            TypeName = "Single"
                        },
                        new
                        {
                            RoomTypeID = 2,
                            AccessibilityFeatures = "Wheelchair Accessible",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Double bed room",
                            HotelId = 1,
                            IsActive = true,
                            TypeName = "Double"
                        },
                        new
                        {
                            RoomTypeID = 3,
                            AccessibilityFeatures = "Wheelchair Accessible, Balcony",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luxury suite with balcony",
                            HotelId = 1,
                            IsActive = true,
                            TypeName = "Suite"
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.State", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateID"));

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateID");

                    b.HasIndex("CountryID");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateID = 1,
                            CountryID = 1,
                            IsActive = true,
                            StateName = "Bagmati"
                        },
                        new
                        {
                            StateID = 2,
                            CountryID = 1,
                            IsActive = true,
                            StateName = "Province 1"
                        },
                        new
                        {
                            StateID = 3,
                            CountryID = 2,
                            IsActive = true,
                            StateName = "Delhi"
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Description = "System Administrator",
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            Description = "Hotel Manager",
                            IsActive = true,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleID = 3,
                            Description = "Front Desk Staff",
                            IsActive = true,
                            RoleName = "Receptionist"
                        },
                        new
                        {
                            RoleID = 4,
                            Description = "Hotel Guest",
                            IsActive = true,
                            RoleName = "Guest"
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Cancellation", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Cancellations")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Guest", "Guest")
                        .WithMany("Feedbacks")
                        .HasForeignKey("GuestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBooking.Core.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Guest", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Country", "Country")
                        .WithMany("Guests")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelBooking.Core.Domain.Entities.State", "State")
                        .WithMany("Guests")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelBooking.Core.Domain.Entities.User", "User")
                        .WithMany("Guests")
                        .HasForeignKey("UserID");

                    b.Navigation("Country");

                    b.Navigation("State");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.HotelImage", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Hotel", "Hotel")
                        .WithMany("HotelImgs")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Payment", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.PaymentBatch", "PaymentBatch")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentBatchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelBooking.Core.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentBatch");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.PaymentBatch", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.User", "User")
                        .WithMany("PaymentBatches")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Refund", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBooking.Core.Domain.Entities.User", "ProcessedByUser")
                        .WithMany("RefundsProcessed")
                        .HasForeignKey("ProcessedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBooking.Core.Domain.Entities.RefundMethod", "RefundMethod")
                        .WithMany("Refunds")
                        .HasForeignKey("RefundMethodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("ProcessedByUser");

                    b.Navigation("RefundMethod");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBooking.Core.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.ReservationGuest", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Guest", "Guest")
                        .WithMany("ReservationGuests")
                        .HasForeignKey("GuestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBooking.Core.Domain.Entities.Reservation", "Reservation")
                        .WithMany("ReservationGuests")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Room", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.RoomAmenity", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Amenity", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBooking.Core.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.RoomType", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Hotel", "Hotel")
                        .WithMany("RoomTypes")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.State", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.User", b =>
                {
                    b.HasOne("HotelBooking.Core.Domain.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Country", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("States");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Guest", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("ReservationGuests");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("HotelImgs");

                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.PaymentBatch", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.RefundMethod", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Cancellations");

                    b.Navigation("Feedbacks");

                    b.Navigation("Payments");

                    b.Navigation("ReservationGuests");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.RoomType", b =>
                {
                    b.Navigation("RoomAmenities");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.State", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("PaymentBatches");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RefundsProcessed");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelBooking.Core.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
